import {
  CogIcon,
  HomeIcon,
  BillIcon,
  AsteriskIcon,
  InfoOutlineIcon,
  EarthGlobeIcon,
  DocumentSheetIcon,
  LockIcon,
  UserIcon,
  ColorWheelIcon,
  CalendarIcon,
  HighlightIcon,
} from '@sanity/icons'

export const myStructure = (S: any) =>
  S.list()
    .title('Content')
    .items([
      S.listItem()
        .title('Site Settings')
        .icon(CogIcon)
        .child(S.document().schemaType('siteSettings').documentId('siteSettings')),
      S.documentTypeListItem('exhibition').title('Exhibitions').icon(CalendarIcon),
      S.documentTypeListItem('artist').title('Artists').icon(UserIcon),
      S.listItem()
        .title('Pages')
        .icon(BillIcon)
        .child(
          S.list()
            .title('Pages')
            .items([
              S.listItem()
                .title('Home')
                .icon(HomeIcon)
                .child(S.document().schemaType('homePage').documentId('homePage')),
              S.listItem()
                .title('Information')
                .icon(InfoOutlineIcon)
                .child(S.document().schemaType('informationPage').documentId('informationPage')),
              S.listItem()
                .title('Accessibility')
                .icon(EarthGlobeIcon)
                .child(
                  S.document().schemaType('accessibilityPage').documentId('accessibilityPage'),
                ),
              S.listItem()
                .title('Privacy')
                .icon(LockIcon)
                .child(S.document().schemaType('privacyPage').documentId('privacyPage')),
              S.listItem()
                .title('Terms')
                .icon(DocumentSheetIcon)
                .child(S.document().schemaType('termsPage').documentId('termsPage')),
            ]),
        ),
      ...S.documentTypeListItems().filter(
        (listItem: any) =>
          ![
            'siteSettings',
            'artist',
            'artwork',
            'exhibition',
            'press',
            'homePage',
            'informationPage',
            'accessibilityPage',
            'privacyPage',
            'termsPage',
          ].includes(listItem.getId()),
      ),
    ])
